---
abstract: 'read mail and send to wiki'
author:
  - 'ChinaXing(陈云星) <chen.yack@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail2Wiki
requires:
  Digest::MD5: 0
  Email::MIME: 0
  Encode: 0
  Exporter: 0
  File::Slurp: 0
  FindBin: 0
  Module::Runtime: 0
  Mojo::DOM: 0
  Mojo::UserAgent: 0
  Mojo::Util: 0
  Moose: 0
  Net::IMAP::Client: 0
  Time::Piece: 0
  YAML::XS: 0
  base: 0
  utf8: 0
version: 0.007
