---
abstract: 'read mail and send to wiki'
author:
  - 'ChinaXing(陈云星) <chen.yack@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail2Wiki
version: 0.001
